version: 0.2
phases:
  pre_build:
    commands:
      - |
          image_name=apex-redirect
          commit_hash=${CODEBUILD_RESOLVED_SOURCE_VERSION}
          echo "Building commit ${commit_hash}"
          $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION 2>/dev/null)
          docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${image_name}:latest >/dev/null || true

  build:
    commands:
      - docker build --cache-from $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${image_name}:latest -t ${image_name}:${commit_hash} .

  post_build:
    commands:
      - |
          export REGIONS=${REGIONS_LIST:-$(aws ssm get-parameter --name '/bootstrap/account-regions' --query Parameter.Value --output text)}
          echo Pushing to $REGIONS

      - |
          export IFS=","
          for REGION in $REGIONS; do
            $(aws ecr get-login --no-include-email --region $REGION 2>/dev/null)
            docker tag ${image_name}:${commit_hash} $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/${image_name}:${commit_hash}
            docker tag ${image_name}:${commit_hash} $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/${image_name}:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/${image_name}:${commit_hash} >/dev/null
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/${image_name}:latest >/dev/null
          done

      - aws ssm put-parameter --overwrite --name "/deployments/${image_name}/latest" --value ${commit_hash} --type String
