#! /usr/bin/env bash

set -x

if [ -z "$1" ]; then
    echo $0 Launching Child
    $0 ${CERTBOT_DOMAIN} &
    exit 0

else
    DOMAIN=$1
    while [ ! -f /etc/letsencrypt/live/${CERTBOT_DOMAIN}/fullchain.pem ]; do sleep 5; done

    for ip in $(dig +short ${DOMAIN} A); do
      echo $0 Registering with $ip
      curl -v http://$ip/.well-known/acme-fullchain -H "Host: ${DOMAIN}" -D @/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
      curl -v http://$ip/.well-known/acme-privkey -H "Host: ${DOMAIN}" -D @/etc/letsencrypt/live/${DOMAIN}/privkey.pem
    done

    mv /etc/letsencrypt/live/${DOMAIN}/fullchain.pem /etc/letsencrypt/live/${DOMAIN}/fullchain.loaded
    mv /etc/letsencrypt/live/${DOMAIN}/privkey /etc/letsencrypt/live/${DOMAIN}/privkey.loaded

fi
