#! /usr/bin/env bash

echo $0 Entering ${CERTBOT_DOMAIN}

cat <<EOF >/etc/nginx/conf.d/${CERTBOT_DOMAIN}.conf
server {
    listen 443 ssl;
    server_name ${CERTBOT_DOMAIN};
    ssl_certificate /etc/letsencrypt/live/${CERTBOT_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${CERTBOT_DOMAIN}/privkey.pem;

    location ~ (.*) {
        rewrite ^ $scheme://www.$https_host$request_uri permanent;
    }
}
EOF

openresty -s reload

echo $0 Done ${CERTBOT_DOMAIN}
exit 0
